# https://github.com/redis-developer/redismod-docker-compose/blob/main/docker-compose.yml
version: '3.9'
services:
  redis:
    image: redis/redis-stack-server:latest
    # redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    # command: redis-server --save 20 1 --loglevel warning
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # --loadmodule /usr/lib/redis/modules/redistimeseries.so
    #   --loadmodule /usr/lib/redis/modules/redisgraph.so
    # --loadmodule /usr/lib/redis/modules/redisai.so
    #      ONNX redisai_onnxruntime/redisai_onnxruntime.so
    #      TF redisai_tensorflow/redisai_tensorflow.so
    #      TFLITE redisai_tflite/redisai_tflite.so
    #      TORCH redisai_torch/redisai_torch.so   
    volumes: 
      - .redis:/data
    # entrypoint: >
    #   redis-server
    #     --loadmodule /usr/lib/redis/modules/rejson.so
    #     --loadmodule /usr/lib/redis/modules/redisearch.so
    #     --appendonly yes
volumes:
  redis:
    driver: local